platform:
  - x86

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  PACKAGE: datakit
  PINS: "datakit-server.dev:. datakit-server-9p.dev:. datakit-github.dev:. datakit-client.dev:. datakit-client-9p.dev:."

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
  - call %CYG_ROOT%\bin\bash.exe -lc 'cd ${APPVEYOR_BUILD_FOLDER}; make exe COMMIT'

artifacts:
  - path: "com.docker.db.exe"
  - path: "COMMIT"

cache:
  - '%CYG_ROOT%\home\appveyor\.opam'
